apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: destination-service
spec:
  hosts:
    - destination-service
  http:
  - route:
    - destination:
        host: destination-service
        subset: B1
      weight: 50 # 50% of traffic from pods in node1
      match:
        sourceLabels:
          app: A1
    - destination:
        host: destination-service
        subset: B2
      weight: 50 # 50% of traffic from pods in node1
      match:
        sourceLabels:
          app: A1
