apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hello-svc
spec:
  host: hello-svc.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: europe-west8/europe-west8-a/*
          to:
            "europe-west8/europe-west8-c/*": 1
            "europe-west8/europe-west8-a/*": 99
    outlierDetection:
      consecutive5xxErrors: 100
      interval: 1s
      baseEjectionTime: 1m
