apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-controller
  # namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-controller
  template:
    metadata:
      labels:
        app: pod-controller
    spec:
      containers:
        - name: pod-controller
          image: alazidis/lpa-controller:0.0.2
          imagePullPolicy: Always
      serviceAccountName: full-access-sa
