name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - 'placement/**'

  pull_request:
    branches:
      - main
    paths:
      - 'placement/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3.6.0
        with:
          node-version: lts/Hydrogen
          cache: 'npm'

      - name: Install dependencies
        working-directory: placement
        run: npm install

      - name: TS check
        working-directory: placement
        run: npm run ts-check

      - name: Linting
        working-directory: placement
        run: npm run lint